dependencies:
  build:
    - python:3.6

build_targets:
  - name: build_docs
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-service-account.json
    commands:
      - pip install gsutil
      - ./.yourbase-activate-gcloud-service-account
      - pip install -r requirements.txt
      - mkdocs build
      - gsutil -o Credentials:gs_service_key_file=/tmp/gcloud-service-account.json -m rsync -d -r ./site/ gs://docs.spankpay.com

ci:
  builds:
    - name: build_docs
      build_target: build_docs
